	-- Code generated by gen_cpu.py ends above

	local m, cb = 0, 0
	for i = 0, 0xFF do
		if opcode_map[i] ~= nil then
			m = m + 1
		end
		if opcode_map_cb[i] ~= nil then
			cb = cb + 1
		end
	end
	print(string.format("CPU opcodes implemented: %d/245 CB prefix: %d/256", m, cb))

	return cpu
end
